/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista;

import ec.edu.ister.controlador.ConexionMysql;
import ec.edu.ister.controlador.ValidacionesDeCampos;
import ec.edu.ister.modelo.Moto;
import ec.edu.ister.modelo.Motos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandra
 */
public class InterfaceMotos extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceMotos
     */
    Moto moto = new  Moto();
    Motos motos = new Motos();
    ConexionMysql obConexionMysql = new ConexionMysql();
    Connection obConnection = obConexionMysql.getConexion();
    public InterfaceMotos() {
        initComponents();
        buscar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        tbnSeleccionar = new javax.swing.JMenuItem();
        txtAno = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btbLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tbnSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbnSeleccionar.setText("SELECCIONAR");
        tbnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnSeleccionarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(tbnSeleccionar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAno.setBorder(null);
        txtAno.setOpaque(false);
        txtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoKeyTyped(evt);
            }
        });
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 180, 40));

        txtSerie.setBorder(null);
        txtSerie.setOpaque(false);
        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerieKeyTyped(evt);
            }
        });
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 180, 40));

        txtPrecio.setBorder(null);
        txtPrecio.setOpaque(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 80, 40));

        txtDescripcion.setBorder(null);
        txtDescripcion.setOpaque(false);
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 180, 40));

        txtCantidad.setBorder(null);
        txtCantidad.setOpaque(false);
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 80, 30));

        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 180, 40));

        txtCodigo.setBorder(null);
        txtCodigo.setOpaque(false);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 180, 40));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 110, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 110, -1));

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 110, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 110, -1));

        btbLimpiar.setText("Limpiar");
        btbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 110, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabla.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1240, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ister/imagenes/motos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        motos.setModificar(Integer.parseInt(txtCodigo.getText()), txtNombre.getText(), Integer.parseInt(txtCantidad.getText()),txtDescripcion.getText(), Double.parseDouble(txtPrecio.getText()), Integer.parseInt(txtSerie.getText()), Integer.parseInt(txtAno.getText()));
        limpiar();
        buscar("");
    }//GEN-LAST:event_btnModificarActionPerformed
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar(txtCodigo.getText());
        limpiar();
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        motos.setRegistroDeMotos(Integer.parseInt(txtCodigo.getText()), txtNombre.getText(), Integer.parseInt(txtCantidad.getText()),txtDescripcion.getText(), Double.parseDouble(txtPrecio.getText()), Integer.parseInt(txtSerie.getText()), Integer.parseInt(txtAno.getText()));
        limpiar();
        buscar("");
    }//GEN-LAST:event_btnAnadirActionPerformed
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        motos.setEliminarAutos(Integer.parseInt(txtCodigo.getText()));
        limpiar();
        buscar("");
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void tbnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnSeleccionarActionPerformed
        filas();
    }//GEN-LAST:event_tbnSeleccionarActionPerformed

    private void btbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLimpiarActionPerformed
       limpiar();
       buscar("");
    }//GEN-LAST:event_btbLimpiarActionPerformed
    ValidacionesDeCampos obValidacionesDeCampos = new ValidacionesDeCampos();
    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        obValidacionesDeCampos.enteros(evt);
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        obValidacionesDeCampos.alfabeticos(evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        obValidacionesDeCampos.enteros(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // No requiere valdiar, el campo puede tener numeros letras y caracteres especiales.....
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        obValidacionesDeCampos.flotanes(evt);
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyTyped
        obValidacionesDeCampos.enteros(evt);
    }//GEN-LAST:event_txtSerieKeyTyped

    private void txtAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoKeyTyped
        obValidacionesDeCampos.enteros(evt);
    }//GEN-LAST:event_txtAnoKeyTyped
    public void buscar(String codigo) {
        DefaultTableModel molde=  new DefaultTableModel();
        String sql;
        Statement ps;
        ResultSet rs;
        
        molde.addColumn("CÓDIGO");
        molde.addColumn("NOMBRE");
        molde.addColumn("CANTIDAD");
        molde.addColumn("DESCRIPCION");
        molde.addColumn("PRECIO");
        molde.addColumn("SERIE");
        molde.addColumn("AÑO");
        tabla.setModel( molde ); 
        if ( "".equals(codigo) ) {    
            sql = "SELECT * FROM motos";
        } else {                       
            sql = "SELECT * FROM motos WHERE codigo='"+codigo+"';";        }
        String[] tupla = new String[7];
        try {
            ps = obConnection.createStatement();
            rs = ps.executeQuery(sql);
            while (rs.next()) {
                tupla[0] = rs.getString(1);                
                tupla[1] = rs.getString(2);
                tupla[2] = rs.getString(3);                
                tupla[3] = rs.getString(4);
                tupla[4] = rs.getString(5);                
                tupla[5] = rs.getString(6);
                tupla[6] = rs.getString(7);
                molde.addRow(tupla);
            }
            tabla.setModel( molde );
        } catch (SQLException ex) {
            ex.toString();
        }
    }

    public void limpiar(){
        txtAno.setText("");
        txtCantidad.setText("");
        txtCodigo.setText("");
        txtDescripcion.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtSerie.setText("");
    }
    public void filas(){
    if (tabla.getSelectedRow() >= 0) {
            txtCodigo.setText(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());
            txtNombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
            txtCantidad.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
            txtDescripcion.setText(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
            txtPrecio.setText(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
            txtSerie.setText(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());
            txtAno.setText(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un registro..!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbLimpiar;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JMenuItem tbnSeleccionar;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
